ghost_shopper/auth/urls.py
from django.urls import path

from . import views


app_name = 'auth'


urlpatterns = [
    path('signup/performer', views.SignUpView.as_view(), name='signup_performer'),
    path('logout', views.UserLogoutView.as_view(), name='logout'),
    path('login', views.UserLoginView.as_view(), name='login'),
    path('change-password', views.PasswordChangeView.as_view(), name='change_password'),
    path('reset-password', views.PasswordResetView.as_view(), name='reset-password'),
    path('reset-password/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm')
]

ghost_shopper/check/urls.py
from django.urls import path

from . import views

app_name = 'check'


urlpatterns = [

    # different check list urls
    path('', views.ChecksListView.as_view(), name='list'),
    path('available', views.AvailableChecksListView.as_view(), name='available'),
    path('performer/<int:pk>/closed', views.PerformerClosedChecksListView.as_view(), name='performer-closed'),
    path('performer/<int:pk>/current', views.PerformerCurrentChecksListView.as_view(), name='performer-current'),

    path('create', views.CheckCreateView.as_view(), name='create'),
    path('<int:pk>', views.CheckDetailView.as_view(), name='detail'),
    path('<int:pk>/update', views.CheckUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.CheckDeleteView.as_view(), name='delete'),
    path('<int:pk>/excel', views.CheckFileGenerateView.as_view(), name='excel'),

    # check performer requests urls
    path('<int:pk>/appoint-performer', views.CheckAppointPerformerView.as_view(), name='appoint-performer'),
    path('<int:pk>/perform-request/create',
         views.CheckPerformRequestCreateView.as_view(),
         name='create-perform-request'),
    path('perform-request/<int:pk>/approve',
         views.CheckPerformRequestApproveView.as_view(),
         name='approve-perform-request'),

    # check change statuses urls
    path('<int:pk>/change-status/available', views.CheckMakeAvailableView.as_view(), name='make-available'),
    path('<int:pk>/make-processing', views.CheckMakeProcessingView.as_view(), name='make-processing'),
    path('<int:pk>/change-status/filled', views.CheckMakeFilledView.as_view(), name='make-filled'),
    path('<int:pk>/change-status/rework', views.CheckSendForReworkView.as_view(), name='make-rework'),
    path('<int:pk>/change-status/conformation',
        views.CheckSendForCustomerConformationView.as_view(),
        name='make-conformation'),
    path('<int:pk>/change-status/close', views.CheckCloseView.as_view(), name='make-close'),
]

ghost_shopper/core/urls.py
from django.urls import path

from . import views


app_name = 'core'


urlpatterns = [
    path('my-organisation', views.MyOrganisationUpdateView.as_view(), name='my-organisation'),

    path('check-kind', views.CheckKindListView.as_view(), name='check-kind-list'),
    path('check-kind/<int:pk>/update', views.CheckKindUpdateView.as_view(), name='check-kind-update'),
    path('check-kind/<int:pk>/delete', views.CheckKindDeleteView.as_view(), name='check-kind-delete'),

    path('section-name', views.SectionListView.as_view(), name='section_name_list'),
    path('section-name/<int:pk>/update', views.SectionUpdateView.as_view(), name='section-name-update'),
    path('section-name/<int:pk>/delete', views.SectionDeleteView.as_view(), name='section-name-delete'),

    path('city', views.CityListView.as_view(), name='city-list'),
    path('city/<int:pk>/delete', views.CityDeleteView.as_view(), name='city-delete'),

    path('car-brand', views.CarBrandListView.as_view(), name='car-brand-list'),
    path('car-brand/<int:pk>/delete', views.CarBrandDeleteView.as_view(), name='car-brand-delete'),

    path('car-brand/<int:pk>/models', views.CarModelListView.as_view(), name='car-model-list'),
    path('car-model/<int:pk>/delete', views.CarModelDeleteView.as_view(), name='car-model-delete'),

    path(
        'performer-letters-templates',
        views.PerformerLettersTemplateUpdateView.as_view(),
        name='performer-letters-template'
    )

]

ghost_shopper/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('ghost_shopper.index_page.urls', namespace='index_page')),

    path('summernote/', include('django_summernote.urls')),

    path('core/', include('ghost_shopper.core.urls', namespace='core')),
    path('admin/', include('ghost_shopper.admin.urls', namespace='admin')),
    path('project/', include('ghost_shopper.project.urls', namespace='project')),
    path('profile/', include('ghost_shopper.auth.urls', namespace='auth')),
    path('profile/', include('ghost_shopper.user_profile.urls', namespace='profile')),
    path('check/', include('ghost_shopper.check.urls', namespace='check')),
    path('chat/', include('ghost_shopper.organisation_chat.urls', namespace='chat')),
    path('checklist/', include('ghost_shopper.checklist.urls', namespace='checklist')),
    path('organisation/', include('ghost_shopper.organisation_tree.urls', namespace='organisation')),
    path('instruction/', include('ghost_shopper.instruction.urls', namespace='instruction')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ghost_shopper/user_profile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from . import forms


app_name = 'profile'


urlpatterns = [
    path('', views.UserListView.as_view(), name='list'),
    path('performers/', views.PerformerListView.as_view(), name='performers'),

    path('create/staff', views.UserCreateView.as_view(form_class=forms.StaffCreationForm), name='create-staff'),
    path('create/performer', views.UserCreateView.as_view(form_class=forms.PerformerCreationForm), name='create-performer'),

    path('<int:pk>', views.UserProfileDetail.as_view(), name='detail'),
    path('<int:pk>/update', views.ProfileUpdateView.as_view(), name='update'),
    path('<int:pk>/permissions', views.UserPermissionsUpdate.as_view(), name='permissions-update'),
    path('<int:pk>/delete', views.UserDeleteView.as_view(), name='delete'),

    path('auto/<int:pk>/delete', views.PerformerAutoDeleteView.as_view(), name='delete-auto'),

    path('approve-request', views.PerformerApprovalRequestListView.as_view(), name='approval-request-list'),
    path('<int:pk>/approval-request/create',
         views.PerformerApprovalRequestCreateView.as_view(),
         name='approval_request'),
    path('<int:pk>/approval-request/accept',
         views.PerformerApprovalRequestAcceptView.as_view(),
         name='approval-request-accept'),
    path('<int:pk>/approval-request/decline',
         views.PerformerApprovalRequestDeclineView.as_view(),
         name='approval-request-decline'),

    path('autocomplete', views.UserAutocompleteView.as_view(), name='autocomplete'),
    path('autocomplete/performer', views.PerformerAutocompleteView.as_view(), name='performer-autocomplete'),
    path('autocomplete/car-brand', views.PerformerCarBrandAutocompleteView.as_view(), name='car-brand-autocomplete'),
    path('autocomplete/car-model', views.PerformerCarModelAutocompleteView.as_view(), name='car-model-autocomplete')

]

templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	{% block meta %}

	{% endblock %}

	<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/icons/icomoon/styles.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap_limitless.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/components.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/colors.min.css' %}">
	<!-- /global stylesheets -->

	<!-- Core JS files -->
    <script src="{% static 'assets/js/main/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/main/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/loaders/blockui.min.js' %}"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
    <script src="{% static 'assets/js/plugins/visualization/d3/d3.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/visualization/d3/d3_tooltip.js' %}"></script>
    <script src="{% static 'assets/js/plugins/forms/styling/switchery.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/forms/selects/bootstrap_multiselect.js' %}"></script>
    <script src="{% static 'assets/js/plugins/ui/moment/moment.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/ui/perfect_scrollbar.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins/loaders/progressbar.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
	<!-- /theme JS files -->

    {% block css %}

    {% endblock %}

</head>

<body>

	<!-- NAVBAR-->
	<div class="navbar navbar-expand-md navbar-dark" style="background: #808080;">

        <!-- NAVBAR LOGO -->
        <div class="navbar-brand wmin-200">
            {% block logo %}

            {% endblock %}
		</div><!-- /NAVBAR LOGO -->

        {% block navbar %}

        {% endblock %}

	</div><!-- /NAVBAR-->


	<!-- PAGE HEADER -->
	<div class="page-header">

		<div class="page-header-content header-elements-md-inline">
			<div class="page-title d-flex">
                {% if request.META.HTTP_REFERER %}
                    <div class="back-button d-flex align-items-center mr-2">
                        <a href="{{ request.META.HTTP_REFERER  }}">
                            <i class="icon-previous icon-2x text-black-50"></i>
                        </a>
                    </div>
                {% endif %}

				<h3 class="text-black-50">
                    {% block page-header %}

				    {% endblock %}
                </h3>
				<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
			</div>

			<div class="header-elements d-none mb-3 mb-md-0">
			    {% block header-buttons %}

			    {% endblock %}
			</div>
		</div>
	</div><!-- /PAGE HEADER -->


	<!-- PAGE CONTENT -->
	<div class="page-content pt-0">

        {% block sidebar %}

        {% endblock %}

		<!-- Main content -->
		<div class="content-wrapper">

			<!-- Content area -->
			<div class="content">

                {% block content %}
                
                {% endblock %}


			</div>
			<!-- /content area -->

		</div>
		<!-- /main content -->

	</div><!-- /PAGE CONTENT -->


	<!-- FOOTER -->
	<div class="navbar navbar-expand-lg navbar-light">
		<div class="text-center d-lg-none w-100">
			<button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
				<i class="icon-unfold mr-2"></i>
				Footer
			</button>
		</div>

		<div class="navbar-collapse collapse d-flex justify-content-center" id="navbar-footer">
			<span class="navbar-text">
				&copy; <span class="current-year"></span> {{ index_page.company_name }}
			</span>

		</div>
	</div>
	<!-- /FOOTER -->


    {% block loader %}

    {% endblock %}

    <script>
        const currentYear = new Date().getFullYear();
        $('.current-year').html(currentYear)
    </script>

    {% block script %}
    
    {% endblock %}

</body>
</html>

templates/base/base_app.html
{% extends 'base/base.html' %}

{% block logo %}

    <a href="{% url 'profile:detail' user.id %}" class="d-inline-block">
        {% if index_page.logo %}
            <img src="{{ index_page.logo.url }}" alt="">
        {% endif %}
    </a>
{% endblock %}


{% block navbar %}

    <!-- TOGGLE BUTTON -->
    <div class="d-md-none">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-tree5"></i>
        </button>
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div><!-- /TOGGLE BUTTON -->


    <!-- NAVBAR MENU -->
    <div class="collapse navbar-collapse" id="navbar-mobile">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                    <i class="icon-paragraph-justify3"></i>
                </a>
            </li>
        </ul>
        <span class="badge bg-light shadow-1 text-indigo-700 ml-md-auto mr-md-3">{{ request.user.status }}</span>


        <!-- NEWS WIDGET -->
        <ul class="navbar-nav">
            {% if not user.is_performer %}

            <li class="nav-item dropdown">
                <a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown">
                    <i class="icon-bell2"></i>
                    <span class="d-md-none ml-2">Новости</span>
                    <span class="badge badge-pill badge-mark border-orange-400 ml-auto ml-md-0"></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                    <div class="dropdown-content-header">
                        <h4 class="font-weight-semibold text-black-50">Новости</h4>
                    </div>
                    <div class="dropdown-content-body dropdown-scrollable">
                        <ul class="media-list">
                            {% for news in user.news_feed.news.all|slice:":15" %}
                                <li class="media">
                                    <div class="media-body text-black-50">
                                        {{ news.body|safe }}
                                        <div class="font-size-sm text-muted mt-1">{{ news.created|date:'Y-m-d H:i' }}</div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="dropdown-content-footer bg-light">
                    </div>
                </div>
            </li>
            {% endif %}

            <li class="nav-item">
                <a href="{% url 'auth:logout' %}" class="navbar-nav-link" help="Выйти"><i class="icon-switch2"></i></a>
            </li>
        </ul><!-- NEWS WIDGET -->


    </div><!-- /NAVBAR MENU -->

{% endblock %}


{% block sidebar %}
    <!-- Main sidebar -->
    <div class="sidebar sidebar-light sidebar-main sidebar-expand-md align-self-start">
        <!-- Sidebar mobile toggler -->
        <div class="sidebar-mobile-toggler text-center">
            <a href="#" class="sidebar-mobile-main-toggle">
                <i class="icon-arrow-left8"></i>
            </a>
            <span class="font-weight-semibold">Main sidebar</span>
            <a href="#" class="sidebar-mobile-expand">
                <i class="icon-screen-full"></i>
                <i class="icon-screen-normal"></i>
            </a>
        </div>
        <!-- /sidebar mobile toggler -->

        <!-- Sidebar content -->
        <div class="sidebar-content">
            <!-- Navigation -->
            <div class="card card-sidebar-mobile">
                <div class="card-body p-0">
                    <ul class="nav nav-sidebar" data-nav-type="accordion">

                        <!-- CUSTOMER LINKS -->
                        {% if user.is_customer %}
                            <li class="nav-item">
                                <a href="{{ user.get_absolute_url }}" class="nav-link text-black-50">
                                    <i class="icon-home2"></i><span>Профиль</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'organisation:detail' user.profile.organisation_tree_node_id %}" class="nav-link text-black-50">
                                    <i class="icon-tree6"></i><span>Организация</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'organisation:current-checks' user.profile.organisation_tree_node_id %}" class="nav-link text-black-50">
                                    <i class="icon-spinner10"></i><span>Текущие проверки</span>
                                    {% if current_checks_number != 0 %}
                                        <span class="badge bg-green-400 align-self-center ml-auto">{{ current_checks_number }}</span>
                                    {% endif %}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'organisation:checks' user.profile.organisation_tree_node_id %}" class="nav-link text-black-50">
                                    <i class="icon-finish"></i><span>Завершенные проверки</span></a>
                            </li>
                            <!-- /CUSTOMER LINKS -->

                        <!-- PERFORMER LINKS -->
                        {% elif user.is_performer %}
                            <li class="nav-item">
                                <a href="{{ user.get_absolute_url }}" class="nav-link text-black-50">
                                    <i class="icon-home2"></i><span>Профиль</span>
                                </a>
                            </li>
                            {% if user.performer_profile.is_approved %}
                                <li class="nav-item">
                                    <a href="{% url 'check:available' %}" class="nav-link text-black-50">
                                        <i class="icon-copy"></i><span>Доступные проверки</span>
                                        {% if available_checks_number != 0 %}
                                            <span class="badge bg-blue-400 align-self-center ml-auto">{{ available_checks_number }}</span>
                                        {% endif %}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'check:performer-current' user.id %}" class="nav-link text-black-50">
                                        <i class="icon-spinner10"></i><span>Текущие проверки</span>
                                        {% if current_checks_number != 0 %}
                                            <span class="badge bg-green-400 align-self-center ml-auto">{{ current_checks_number }}</span>
                                        {% endif %}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'check:performer-closed' user.id %}" class="nav-link text-black-50"><i class="icon-finish"></i><span>Завершенные проверки</span></a>
                                </li>
                            {% else %}
                                <li class="nav-item"><a class="nav-link disabled">Функции будут доступны после одобрения профиля</a></li>

                            {% endif %}


                        <!-- STAFF LINKS -->
                        {% elif user.is_staff %}
                            <li class="nav-item">
                                <a href="{{ user.get_absolute_url }}" class="nav-link text-black-50">
                                    <i class="icon-home2"></i><span>Профиль</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'organisation:list' %}" class="nav-link text-black-50"><i class="icon-tree6"></i><span>Организации</span></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'project:list' %}" class="nav-link text-black-50"><i class="icon-files-empty2"></i><span>Проект</span></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'check:list' %}" class="nav-link text-black-50"><i class="icon-file-text2"></i><span>Проверки</span></a>
                            </li>

                            <li class="nav-item">
                                <a href="{% url 'instruction:list' %}" class="nav-link text-black-50"><i class="icon-puzzle3"></i><span>Инструкции</span></a>
                            </li>
                            
                            <li class="nav-item nav-item-submenu">
                                <a href="{% url 'profile:list' %}" class="nav-link text-black-50"><i class="icon-users"></i><span>Пользователи</span></a>
                                <ul class="nav nav-group-sub" data-submenu-title="Пользователи">
                                    <li class="nav-item"><a href="{% url 'profile:list' %}" class="nav-link">Все</a></li>
                                    <li class="nav-item"><a href="{% url 'profile:list' %}?is_staff=true" class="nav-link">Персонал</a></li>
                                    <li class="nav-item"><a href="{% url 'profile:performers' %}" class="nav-link">Исполнители</a></li>
                                    <li class="nav-item"><a href="{% url 'profile:list' %}?is_customer=true" class="nav-link">Заказчики</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'profile:approval-request-list' %}" class="nav-link text-black-50">
                                    <i class="icon-plus-circle2"></i><span>Заявки на одобрение</span>
                                    {% if approval_requests_number %}
                                        <span class="badge bg-blue-400 align-self-center ml-auto">{{ approval_requests_number }}</span>
                                    {% endif %}

                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'index_page:update' %}" class="nav-link text-black-50"><i class="icon-cogs"></i><span>Главная страница</span></a>
                            </li>
                            <li class="nav-item nav-item-submenu">
                                <a href="#" class="nav-link text-black-50"><i class="icon-wrench"></i> <span>Системные</span></a>
                                <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                                    <li class="nav-item"><a href="{% url 'core:my-organisation' %}" class="nav-link">Моя организация</a></li>
                                    <li class="nav-item"><a href="{% url 'core:check-kind-list' %}" class="nav-link">Типы проверок</a></li>
                                    <li class="nav-item"><a href="{% url 'core:section_name_list' %}" class="nav-link">Секции чеклистов</a></li>
                                    <li class="nav-item"><a href="{% url 'core:car-brand-list' %}" class="nav-link">Марки и модели авто</a></li>
                                    <li class="nav-item"><a href="{% url 'core:city-list' %}" class="nav-link">Города</a></li>
                                    <li class="nav-item"><a href="{% url 'core:performer-letters-template' %}" class="nav-link">Шаблоны</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <!-- /navigation -->

        </div>
        <!-- /sidebar content -->

    </div>
    <!-- /main sidebar -->
{% endblock %}

templates/base/confirm_delete.html
{% extends 'base/base_app.html' %}


{% block content %}
    <div class="card">
        <div class="card-body d-flex justify-content-center">
            Вы уверены что хотите удалить объект {{ object }}
        </div>

        <div class="card-footer d-flex justify-content-center">
            <form method="post">
                {% csrf_token %}
                <input type="submit" value="Удалить" class="btn btn-danger">
            </form>

        </div>
    </div>
{% endblock %}