ghost_shopper/core/urls.py
from django.urls import path

from . import views


app_name = 'core'


urlpatterns = [
    path('my-organisation', views.MyOrganisationUpdateView.as_view(), name='my-organisation'),

    path('check-kind', views.CheckKindListView.as_view(), name='check-kind-list'),
    path('check-kind/<int:pk>/update', views.CheckKindUpdateView.as_view(), name='check-kind-update'),
    path('check-kind/<int:pk>/delete', views.CheckKindDeleteView.as_view(), name='check-kind-delete'),

    path('section-name', views.SectionListView.as_view(), name='section_name_list'),
    path('section-name/<int:pk>/update', views.SectionUpdateView.as_view(), name='section-name-update'),
    path('section-name/<int:pk>/delete', views.SectionDeleteView.as_view(), name='section-name-delete'),

    path('city', views.CityListView.as_view(), name='city-list'),
    path('city/<int:pk>/delete', views.CityDeleteView.as_view(), name='city-delete'),

    path('car-brand', views.CarBrandListView.as_view(), name='car-brand-list'),
    path('car-brand/<int:pk>/delete', views.CarBrandDeleteView.as_view(), name='car-brand-delete'),

    path('car-brand/<int:pk>/models', views.CarModelListView.as_view(), name='car-model-list'),
    path('car-model/<int:pk>/delete', views.CarModelDeleteView.as_view(), name='car-model-delete'),

    path(
        'performer-letters-templates',
        views.PerformerLettersTemplateUpdateView.as_view(),
        name='performer-letters-template'
    )

]

ghost_shopper/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('ghost_shopper.index_page.urls', namespace='index_page')),

    path('summernote/', include('django_summernote.urls')),

    path('core/', include('ghost_shopper.core.urls', namespace='core')),
    path('admin/', include('ghost_shopper.admin.urls', namespace='admin')),
    path('project/', include('ghost_shopper.project.urls', namespace='project')),
    path('profile/', include('ghost_shopper.auth.urls', namespace='auth')),
    path('profile/', include('ghost_shopper.user_profile.urls', namespace='profile')),
    path('check/', include('ghost_shopper.check.urls', namespace='check')),
    path('chat/', include('ghost_shopper.organisation_chat.urls', namespace='chat')),
    path('checklist/', include('ghost_shopper.checklist.urls', namespace='checklist')),
    path('organisation/', include('ghost_shopper.organisation_tree.urls', namespace='organisation')),
    path('instruction/', include('ghost_shopper.instruction.urls', namespace='instruction')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ghost_shopper/core/models.py
""" Technically its not a core module. Here i put all entities that a don't understand where to put them.
    Kind a entities trash.
"""
from django.db import models


class CheckKind(models.Model):
    """Check kind."""
    name = models.CharField(max_length=1000, verbose_name='Название')
    price = models.SmallIntegerField(default=0, verbose_name='Цена')

    def __str__(self):
        return self.name


class MyOrganisation(models.Model):
    """Data about organisation that is necessary for some documents."""
    full_name = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Полное название')
    short_name = models.CharField(max_length=500, null=True, blank=True, verbose_name='Сокращенное название')
    INN = models.CharField(max_length=50, null=True, blank=True, verbose_name='ИНН')
    KPP = models.CharField(max_length=50, null=True, blank=True, verbose_name='КПП')
    account = models.CharField(max_length=50, null=True, blank=True, verbose_name='Расчетный счет')
    address = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Юридический адрес')
    phone_number = models.CharField(max_length=50, null=True, blank=True, verbose_name='Номер телефона')

    bank_name = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Название банка')
    bank_BIC = models.CharField(max_length=25, null=True, blank=True, verbose_name='БИК банка')
    bank_account = models.CharField(max_length=50, null=True, blank=True, verbose_name='Расчетный счет банка')

    @classmethod
    def get(cls):
        instance, _ = cls.objects.get_or_create(id=1)
        return instance


class City(models.Model):
    """  """
    name = models.CharField(max_length=70, verbose_name='Название')

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

    def __str__(self):
        return self.name


class CarBrand(models.Model):
    """ Car brand system model """
    name = models.CharField(max_length=50, verbose_name='Название')

    def __str__(self):
        return self.name


class CarModel(models.Model):
    """ Car model system model """
    brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE, related_name='models', verbose_name='Марка')
    name = models.CharField(max_length=100, verbose_name='Название')

    def __str__(self):
        return self.name


class PerformerLettersTemplates(models.Model):
    """ Model for storing check perform invitation letter body text """

    default_invite = 'Уважаемый, {performer}! \nПредлагаем Вам провести {check}.\n{link}'

    default_apply = 'Уважаемый, {performer}! \nВас одобрили для проведения проверки {check}.\n{link}'

    invite_subject = 'Приглашаем Вас провести проверку'
    invite_message = models.TextField(default=default_invite)

    apply_subject = 'Ваша заявка на проведение проверки одобрена'
    apply_message = models.TextField(default=default_apply)

    @classmethod
    def get(cls):
        instance, _ = cls.objects.get_or_create(id=1)
        return instance

ghost_shopper/core/forms.py
from django import forms
from django.contrib.auth.models import Group

from ghost_shopper.checklist.models import SectionName

from . import models


class MyOrganisationForm(forms.ModelForm):
    class Meta:
        model = models.MyOrganisation
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].widget.attrs['class'] = 'form-control'


class CheckKindForm(forms.ModelForm):
    class Meta:
        model = models.CheckKind
        fields = ('name', 'price')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'})
        }


class SectionNameForm(forms.ModelForm):
    class Meta:
        model = SectionName
        fields = ('value', )
        widgets = {'value': forms.TextInput(attrs={'class': 'form-control'})}


class CityForm(forms.ModelForm):
    class Meta:
        model = models.City
        fields = ('name', )
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'})}


class CarBrandForm(forms.ModelForm):
    class Meta:
        model = models.CarBrand
        fields = ('name', )
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'})}


class CarModelForm(forms.ModelForm):

    class Meta:
        model = models.CarModel
        fields = ('brand', 'name')
        widgets = {'brand': forms.HiddenInput(), 'name': forms.TextInput(attrs={'class': 'form-control'})}


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name', 'permissions')


class PerformerInvitationLetterForm(forms.ModelForm):
    class Meta:
        model = models.PerformerLettersTemplates
        fields = ('invite_message', 'apply_message')
        widgets = {
            'invite_message': forms.TextInput(attrs={'class': 'form-control'}),
            'apply_message': forms.TextInput(attrs={'class': 'form-control'})
        }

ghost_shopper/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import FormMixin, ProcessFormView
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.decorators import method_decorator
from django.forms.models import modelform_factory

from ghost_shopper.auth.decorators import staff_member_required

from ghost_shopper.checklist.models import SectionName

from . import models
from . import forms


@method_decorator(staff_member_required, name='dispatch')
class MyOrganisationUpdateView(LoginRequiredMixin, generic.UpdateView):
    """My organisation singleton class update view."""

    model = models.MyOrganisation
    form_class = forms.MyOrganisationForm
    template_name = 'core/my_organisation.html'
    login_url = reverse_lazy('auth:login')

    def get_success_url(self):
        """Get success url for the view."""
        return reverse_lazy('core:my-organisation')

    def get_object(self, queryset=None):
        """Get my organisation instance."""
        return models.MyOrganisation.get()


class CheckKindListView(LoginRequiredMixin, generic.ListView, FormMixin, ProcessFormView):
    """Check kind list and also create view."""

    model = models.CheckKind
    form_class = forms.CheckKindForm
    template_name = 'core/check-kind-list.html'
    context_object_name = 'check_kinds'
    paginate_by = 20
    login_url = reverse_lazy('auth:login')

    def form_valid(self, form):
        """Redirect user to self if form is valid."""
        form.save()
        return redirect(reverse_lazy('core:check-kind-list'))


class CheckKindUpdateView(LoginRequiredMixin, generic.UpdateView):
    """
    Update check kind.
    """
    model = models.CheckKind
    template_name = 'core/check_kind_update.html'
    context_object_name = 'check_kind'
    form_class = forms.CheckKindForm
    success_url = reverse_lazy('core:check-kind-list')
    login_url = reverse_lazy('auth:login')


@method_decorator(staff_member_required, name='dispatch')
class CheckKindDeleteView(LoginRequiredMixin, generic.DeleteView):
    """Check kind delete view."""

    model = models.CheckKind
    template_name = 'base/confirm_delete.html'
    success_url = reverse_lazy('core:check-kind-list')
    login_url = reverse_lazy('auth:login')


@method_decorator(staff_member_required, name='dispatch')
class SectionListView(LoginRequiredMixin, generic.ListView, FormMixin, ProcessFormView):
    """Section list view."""

    model = SectionName
    form_class = forms.SectionNameForm
    template_name = 'core/section_name_list.html'
    context_object_name = 'sections'
    paginate_by = 20
    login_url = reverse_lazy('auth:login')

    def form_valid(self, form):
        form.save()
        return redirect(reverse_lazy('core:section_name_list'))


@method_decorator(staff_member_required, name='dispatch')
class SectionUpdateView(LoginRequiredMixin, generic.UpdateView):

    model = SectionName
    template_name = 'core/section_name_update.html'
    context_object_name = 'section_name'
    form_class = forms.SectionNameForm
    success_url = reverse_lazy('core:section_name_list')
    login_url = reverse_lazy('auth:login')



@method_decorator(staff_member_required, name='dispatch')
class SectionDeleteView(LoginRequiredMixin, generic.DeleteView):

    model = SectionName
    template_name = 'base/confirm_delete.html'
    success_url = reverse_lazy('core:section_name_list')
    login_url = reverse_lazy('auth:login')


@method_decorator(staff_member_required, name='dispatch')
class CityListView(LoginRequiredMixin, generic.ListView, FormMixin, ProcessFormView):

    model = models.City
    form_class = forms.CityForm
    template_name = 'core/cities_list.html'
    context_object_name = 'cities'
    paginate_by = 20
    login_url = reverse_lazy('auth:login')

    def form_valid(self, form):
        form.save()
        return redirect(reverse_lazy('core:city-list'))


@method_decorator(staff_member_required, name='dispatch')
class CityDeleteView(LoginRequiredMixin, generic.DeleteView):

    model = models.City
    template_name = 'base/confirm_delete.html'
    success_url = reverse_lazy('core:city-list')
    login_url = reverse_lazy('auth:login')


@method_decorator(staff_member_required, name='dispatch')
class CarBrandListView(LoginRequiredMixin, generic.ListView, FormMixin, ProcessFormView):

    model = models.CarBrand
    form_class = forms.CarBrandForm
    template_name = 'core/car_brand_list.html'
    context_object_name = 'car_brands'
    paginate_by = 40
    login_url = reverse_lazy('auth:login')

    def form_valid(self, form):
        form.save()
        return redirect(reverse_lazy('core:car-brand-list'))


@method_decorator(staff_member_required, name='dispatch')
class CarBrandDeleteView(LoginRequiredMixin, generic.DeleteView):

    model = models.CarBrand
    template_name = 'base/confirm_delete.html'
    success_url = reverse_lazy('core:car-brand-list')
    login_url = reverse_lazy('auth:login')
    paginate_by = 20


@method_decorator(staff_member_required, name='dispatch')
class CarModelListView(LoginRequiredMixin, generic.ListView, FormMixin, ProcessFormView):

    model = models.CarModel
    form_class = forms.CarModelForm
    template_name = 'core/car-model-list.html'
    context_object_name = 'car_models'
    paginate_by = 20
    login_url = reverse_lazy('auth:login')

    def get_queryset(self):
        return models.CarModel.objects.filter(brand_id=self.kwargs.get('pk', None))

    def form_valid(self, form):
        model = form.save()
        return redirect(reverse_lazy('core:car-model-list', args=(model.brand_id, )))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'].fields['brand'].initial = get_object_or_404(models.CarBrand, id=self.kwargs.get('pk', None))
        return context


@method_decorator(staff_member_required, name='dispatch')
class CarModelDeleteView(LoginRequiredMixin, generic.DeleteView):

    model = models.CarModel
    template_name = 'base/confirm_delete.html'
    login_url = reverse_lazy('auth:login')

    def get_success_url(self):
        return reverse_lazy('core:car-model-list', args=(self.object.brand_id, ))


class PerformerLettersTemplateUpdateView(generic.View):

    model = models.PerformerLettersTemplates
    template_name = 'core/templates.html'
    form_class = forms.PerformerInvitationLetterForm
    login_url = reverse_lazy('auth:login')

    def get_object(self):
        return models.PerformerLettersTemplates.get()

    def get(self, request, *args, **kwargs):
        context = {'form': self.form_class(instance=self.get_object())}

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(instance=self.get_object(), data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:performer-letters-template'))
        return render(request, self.template_name, {'form': form})

templates/core/car-model-list.html
{% extends 'base/base_app.html' %}


{% block meta %}
    <title>Список моделей</title>
{% endblock %}

{% block page-header %}
    Список моделей
{% endblock %}


{% block header-buttons %}
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#city-form-modal">Создать</button>
{% endblock %}


{% block content %}

    <div class="card">
        <div class="card-header">
            <h3 class="text-black-50 font-weight-bold">
                Список моделей
            </h3>
        </div>

        <div class="card-body d-flex flex-column justify-content-between">
            <div class="results">

                <div class="col">
                    {% for model in car_models %}
                        <div class="d-flex col justify-content-between bg-light m-1 p-2">
                            <div class="col-10 text-black-50 font-weight-bold">{{ model.name }}</div>
                            <div class="col-2">
                                <a href="{% url 'core:car-model-delete' model.id %}" title="Удалить">
                                    <i class="icon-trash text-danger-400"></i>
                                </a>
                            </div>
                        </div>
                    {% empty %}
                        <span class="font-weight-bold text-black-50">У данной марки нет созданных моделей</span>
                    {% endfor %}
                </div>
            </div>
        </div>

        {% if is_paginated %}
            <div class="d-flex justify-content-center mt-3 mb-3">

                <ul class="pagination shadow-1">

                    {% if page_obj.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link page-link-white legitRipple"><<</a></li>
                        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link page-link-white legitRipple"><</a></li>
                    {% endif %}
                    <li class="page-item active"><a href="#" class="page-link page-link-white legitRipple">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>

                    {% if page_obj.has_next %}
                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link page-link-white legitRipple">></a></li>
                        <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link page-link-white legitRipple">>></a></li>
                    {% endif %}
                </ul>
            </div>

        {% endif %}



    </div>


    <div id="city-form-modal" class="modal fade" tabindex="-1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Создать марку автомобиля</h5>
                    <button type="button" class="close" data-dismiss="modal">×</button>
                </div>

                <div class="modal-body">
                    <form method="post" id="city-form">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-link legitRipple" data-dismiss="modal">Закрыть<div class="legitRipple-ripple" style="left: 59.4543%; top: 39.4737%; transform: translate3d(-50%, -50%, 0px); width: 225.28%; opacity: 0;"></div></button>
                    <input type="submit" class="btn bg-primary legitRipple" value="Создать" form="city-form">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/core/car_brand_list.html
{% extends 'base/base_app.html' %}

{% block meta %}
    <title>Список марок автомобилей</title>
{% endblock %}

{% block page-header %}
    Список марок автомобилей
{% endblock %}


{% block header-buttons %}
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#city-form-modal">Создать</button>
{% endblock %}


{% block content %}

    <div class="card">
        <div class="card-header">
            <h3 class="text-black-50 font-weight-bold">Список марок автомобилей</h3>
        </div>

        <div class="card-body d-flex flex-column justify-content-between">
            <div class="results">

                <div class="col">
                    {% for brand in car_brands %}
                        <div class="d-flex col justify-content-between bg-light m-1 p-2">
                            <a class="col-10 text-black-50 font-weight-bold" href="{% url 'core:car-model-list' brand.id %}">{{ brand.name }}</a>
                            <div class="col-2"><a href="{% url 'core:car-brand-delete' brand.id %}" title="Удалить"><i class="icon-trash text-danger-400"></i></a></div>
                        </div>
                        
                    {% empty %}
                        <span class="text-black-50 font-weight-bold">Нет созданных марок автомобилей</span>
                    {% endfor %}
                </div>
            </div>
        </div>

        {% if is_paginated %}
            <div class="d-flex justify-content-center mt-3 mb-3">

                <ul class="pagination shadow-1">

                    {% if page_obj.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link page-link-white legitRipple"><<</a></li>
                        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link page-link-white legitRipple"><</a></li>
                    {% endif %}
                    <li class="page-item active"><a href="#" class="page-link page-link-white legitRipple">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>

                    {% if page_obj.has_next %}
                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link page-link-white legitRipple">></a></li>
                        <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link page-link-white legitRipple">>></a></li>
                    {% endif %}
                </ul>
            </div>

        {% endif %}

    </div>


    <div id="city-form-modal" class="modal fade" tabindex="-1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Создать марку автомобиля</h5>
                    <button type="button" class="close" data-dismiss="modal">×</button>
                </div>

                <div class="modal-body">
                    <form method="post" id="city-form">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-link legitRipple" data-dismiss="modal">Закрыть<div class="legitRipple-ripple" style="left: 59.4543%; top: 39.4737%; transform: translate3d(-50%, -50%, 0px); width: 225.28%; opacity: 0;"></div></button>
                    <input type="submit" class="btn bg-primary legitRipple" value="Создать" form="city-form">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/core/check-kind-list.html
{% extends 'base/base_app.html' %}


{% block header-buttons %}
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#check-form-modal">Создать</button>
{% endblock %}


{% block content %}
    <div class="card">
        <div class="card-header">
            <h3 class="text-black-50 font-weight-bold">
                Типы проверок
            </h3>
        </div>
    </div>

    <div class="card">

        <div class="card-body d-flex flex-column justify-content-between">
            <div class="results">

                <div class="col">
                    {% for kind in check_kinds|slice:":21" %}
                        <div class="d-flex col justify-content-between bg-light m-1 p-2">
                            <div class="col-6 font-weight-bold text-black-50">{{ kind.name }}</div>
                            <div class="col-4 font-weight-bold text-black-50">{{ kind.price }} руб.</div>
                            <div class="col-2">
                                <a href="{% url 'core:check-kind-update' kind.id %}">
                                    <i class="icon-pencil4 mr-2 text-black-50"></i>
                                </a>
                                <a href="{% url 'core:check-kind-delete' kind.id %}">
                                    <i class="icon-trash text-danger-400"></i>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        {% if is_paginated %}
            <div class="d-flex justify-content-center mt-3 mb-3">

                <ul class="pagination shadow-1">

                    {% if page_obj.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link page-link-white legitRipple"><<</a></li>
                        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link page-link-white legitRipple"><</a></li>
                    {% endif %}
                    <li class="page-item active"><a href="#" class="page-link page-link-white legitRipple">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>

                    {% if page_obj.has_next %}
                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link page-link-white legitRipple">></a></li>
                        <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link page-link-white legitRipple">>></a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}

    </div>


    <div id="check-form-modal" class="modal fade" tabindex="-1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Создать город</h5>
                    <button type="button" class="close" data-dismiss="modal">×</button>
                </div>

                <div class="modal-body">
                    <form method="post" id="city-form">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-link legitRipple" data-dismiss="modal">Закрыть<div class="legitRipple-ripple" style="left: 59.4543%; top: 39.4737%; transform: translate3d(-50%, -50%, 0px); width: 225.28%; opacity: 0;"></div></button>
                    <input type="submit" class="btn bg-primary legitRipple" value="Создать" form="city-form">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/core/my_organisation.html
{% extends 'base/base_app.html' %}


{% block meta %}
    <title>Моя организация</title>
{% endblock %}


{% block page-header %}
    Моя организация
{% endblock %}

{% block header-buttons %}
    <input type="submit" form="my-organisation-form" value="Сохранить" class="btn btn-primary">
{% endblock %}


{% block content %}
    <div class="card">
        <div class="card-header">
            <h3 class="text-black-50 font-weight-bold">Моя организация</h3>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="" method="post" id="my-organisation-form">
            {% csrf_token %}
                <div class="form-errors"></div>
                {% for field in form %}
                    <div class="form-group row"><!-- comment -->
                        <label class="col-12 col-form-label col-lg-3 text-black-50 font-weight-bold">{{ field.label }}:</label>
                        <div class="col-12 col-lg-9">{{ field }}</div>
                        {% if field.errors %}
                            <span class="text-danger-400">{{ field.errors.as_text }}</span>
                        {% endif %}
                    </div><!-- /comment-->
                {% endfor %}
                
            </form>
        </div>
    </div>

{% endblock %}

templates/core/section_name_list.html
{% extends 'base/base_app.html' %}


{% block header-buttons %}
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#section-name-form-modal">Создать</button>
{% endblock %}


{% block meta %}
    <title>Секции чек-листа</title>
{% endblock %}


{% block page-header %}
    Секции чек-листа
{% endblock %}

{% block content %}

    <div class="card">

        <div class="card-header">
            <h3 class="text-black-50 font-weight-bold">
                Список секций
            </h3>
        </div>

        <div class="card-body d-flex flex-column justify-content-between">
            <div class="results">

                <div class="col">
                    {% for section_name in sections %}
                        <div class="d-flex col justify-content-between bg-light m-1 p-2">
                            <div class="col-10 font-weight-bold text-black-50">{{ section_name.value }}</div>
                            <div class="col-2">
                                <a href="{% url 'core:section-name-update' section_name.id %}">
                                    <i class="icon-pencil4 text-black-50 mr-2"></i>
                                </a>
                                <a href="{% url 'core:section-name-delete' section_name.id %}">
                                    <i class="icon-trash text-danger-400"></i>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        {% if is_paginated %}
            <div class="d-flex justify-content-center mt-3 mb-3">

                <ul class="pagination shadow-1">

                    {% if page_obj.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link page-link-white legitRipple"><<</a></li>
                        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link page-link-white legitRipple"><</a></li>
                    {% endif %}
                    <li class="page-item active"><a href="#" class="page-link page-link-white legitRipple">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>

                    {% if page_obj.has_next %}
                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link page-link-white legitRipple">></a></li>
                        <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link page-link-white legitRipple">>></a></li>
                    {% endif %}
                </ul>
            </div>

        {% endif %}



    </div>


    <div id="section-name-form-modal" class="modal fade" tabindex="-1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Создать название секции</h5>
                    <button type="button" class="close" data-dismiss="modal">×</button>
                </div>

                <div class="modal-body">
                    <form method="post" id="section-name-form">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-link legitRipple" data-dismiss="modal">Закрыть<div class="legitRipple-ripple" style="left: 59.4543%; top: 39.4737%; transform: translate3d(-50%, -50%, 0px); width: 225.28%; opacity: 0;"></div></button>
                    <input type="submit" class="btn bg-primary legitRipple" value="Создать" form="section-name-form">
                </div>
            </div>
        </div>
    </div>
{% endblock %}