ghost_shopper/check/urls.py
from django.urls import path

from . import views

app_name = 'check'


urlpatterns = [

    # different check list urls
    path('', views.ChecksListView.as_view(), name='list'),
    path('available', views.AvailableChecksListView.as_view(), name='available'),
    path('performer/<int:pk>/closed', views.PerformerClosedChecksListView.as_view(), name='performer-closed'),
    path('performer/<int:pk>/current', views.PerformerCurrentChecksListView.as_view(), name='performer-current'),

    path('create', views.CheckCreateView.as_view(), name='create'),
    path('<int:pk>', views.CheckDetailView.as_view(), name='detail'),
    path('<int:pk>/update', views.CheckUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.CheckDeleteView.as_view(), name='delete'),
    path('<int:pk>/excel', views.CheckFileGenerateView.as_view(), name='excel'),

    # check performer requests urls
    path('<int:pk>/appoint-performer', views.CheckAppointPerformerView.as_view(), name='appoint-performer'),
    path('<int:pk>/perform-request/create',
         views.CheckPerformRequestCreateView.as_view(),
         name='create-perform-request'),
    path('perform-request/<int:pk>/approve',
         views.CheckPerformRequestApproveView.as_view(),
         name='approve-perform-request'),

    # check change statuses urls
    path('<int:pk>/change-status/available', views.CheckMakeAvailableView.as_view(), name='make-available'),
    path('<int:pk>/make-processing', views.CheckMakeProcessingView.as_view(), name='make-processing'),
    path('<int:pk>/change-status/filled', views.CheckMakeFilledView.as_view(), name='make-filled'),
    path('<int:pk>/change-status/rework', views.CheckSendForReworkView.as_view(), name='make-rework'),
    path('<int:pk>/change-status/conformation',
        views.CheckSendForCustomerConformationView.as_view(),
        name='make-conformation'),
    path('<int:pk>/change-status/close', views.CheckCloseView.as_view(), name='make-close'),
]

ghost_shopper/checklist/urls.py
from django.urls import include, path

from . import views

app_name = 'checklist'


urlpatterns = [
    path('constructor/', include('ghost_shopper.checklist.constructor.urls', namespace='constructor')),
    path('<int:pk>', views.ChecklistDetailView.as_view(), name='detail'),
    path('<int:pk>/update', views.ChecklistUpdateView.as_view(), name='update'),
    path('<int:pk>/appeal', views.ChecklistAppealView.as_view(), name='appeal'),
    path('<int:pk>/audio', views.get_checklist_audio, name='audio'),
    path('image/delete', views.delete_image, name='delete-image'),
]

ghost_shopper/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('ghost_shopper.index_page.urls', namespace='index_page')),

    path('summernote/', include('django_summernote.urls')),

    path('core/', include('ghost_shopper.core.urls', namespace='core')),
    path('admin/', include('ghost_shopper.admin.urls', namespace='admin')),
    path('project/', include('ghost_shopper.project.urls', namespace='project')),
    path('profile/', include('ghost_shopper.auth.urls', namespace='auth')),
    path('profile/', include('ghost_shopper.user_profile.urls', namespace='profile')),
    path('check/', include('ghost_shopper.check.urls', namespace='check')),
    path('chat/', include('ghost_shopper.organisation_chat.urls', namespace='chat')),
    path('checklist/', include('ghost_shopper.checklist.urls', namespace='checklist')),
    path('organisation/', include('ghost_shopper.organisation_tree.urls', namespace='organisation')),
    path('instruction/', include('ghost_shopper.instruction.urls', namespace='instruction')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ghost_shopper/check/models.py
from datetime import date, datetime

from django.conf import settings
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.db import models
from django.urls import reverse

from ghost_shopper.core.models import PerformerLettersTemplates
from ghost_shopper.news import event_handlers

from .enums import CHECK_TYPES, CheckStatusesEnum


class UsualChecksManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=CHECK_TYPES['USUAL'])


class Check(models.Model):
    """
    Check object.
    """
    project = models.OneToOneField('project.Project', on_delete=models.SET_NULL, null=True, blank=True,
                                related_name='check_obj', verbose_name='Проект')
    status = models.CharField(max_length=30, choices=tuple(CheckStatusesEnum.values.items()),
                              default=CheckStatusesEnum.CREATED, verbose_name='Статус')
    type = models.CharField(max_length=20, choices=tuple(CHECK_TYPES.items()), default=CHECK_TYPES['USUAL'],
                            verbose_name='Тип')
    kind = models.ForeignKey('core.CheckKind', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Тип')
    start_date = models.DateField(null=True, blank=True, verbose_name='Дата начала')
    deadline = models.DateField(null=True, blank=True, verbose_name='Дедлайн')
    end_date = models.DateField(null=True, blank=True, verbose_name='Окончание')
    target = models.ForeignKey(
        'organisation_tree.OrganisationTreeNode',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name='Цель'
    )
    instruction = models.ForeignKey(
        'instruction.Instruction', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Инструкция')
    performer = models.ForeignKey(
        'user_profile.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='performer',
        verbose_name='Исполнитель')
    curator = models.ForeignKey(
        'user_profile.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='checks',
        verbose_name='Куратор')
    reward = models.PositiveSmallIntegerField(default=0, verbose_name='Награда(руб.)')
    was_sent_to_rework = models.BooleanField(default=False, verbose_name='Была отправлена на доработку')
    was_appealed = models.BooleanField(default=False, verbose_name='Была аппеляция')
    conformation_period = models.PositiveSmallIntegerField('Дней на аппеляцию', default=1)
    comment = models.TextField(blank=True, null=True, verbose_name='Комментарий')

    sent_for_conformation_date = models.DateField(null=True, blank=True)

    objects = models.Manager()
    usual = UsualChecksManager()

    class Meta:
        ordering = ('start_date', )
        verbose_name = 'Проверка'
        verbose_name_plural = 'Проверки'

    @property
    def title(self):
        return self.__str__()

    def __str__(self):
        name = self.target.title if self.target else self.id
        return 'Проверка {}'.format(name)

    def get_absolute_url(self):
        return reverse('check:detail', args=(self.id,))

    def clone(self, new_target=None) -> None:
        """
        Clone this check.
        Returns:
            new_check (Check): new cloned check object.
        """
        instruction = self.instruction
        checklist = self.checklist

        new_check = self
        new_check.id = None
        new_check.project = None
        new_check.target = new_target
        new_check.status = CheckStatusesEnum.AVAILABLE
        new_check.type = CHECK_TYPES['USUAL']
        new_check.instruction = instruction
        new_check.save()
        new_check.checklist.delete()

        checklist.clone(new_check)
        return new_check

    def make_available(self):
        self.status = CheckStatusesEnum.AVAILABLE
        self.save()
        event_handler = event_handlers.CheckAvailableEventHandler(check=self)
        event_handler.handle()

    def make_processing(self):
        self.status = CheckStatusesEnum.PROCESSING
        self.save()
        self.perform_requests.all().delete()
        performer_name = self.performer.get_full_name() if self.performer else self.performer_typed
        event_handler = event_handlers.CheckProcessingEventHandler(self, performer_name)
        event_handler.handle()

    def make_filled(self):
        self.status = CheckStatusesEnum.FILLED
        self.save()
        event_handler = event_handlers.CheckFilledEventHandler(check=self)
        event_handler.handle()

    def send_for_rework(self):
        self.status = CheckStatusesEnum.PROCESSING
        self.was_sent_to_rework = True
        self.save()
        event_handler = event_handlers.CheckSentToReworkEventHandler(check=self)
        event_handler.handle()

    def send_for_conformation(self):
        self.status = CheckStatusesEnum.CONFORMATION
        self.sent_for_conformation_date = date.today()
        self.save()
        event_handler = event_handlers.CheckSentForConformation(check=self)
        event_handler.handle()

    def appeal(self):
        self.status = CheckStatusesEnum.APPEAL
        self.was_appealed = True
        self.save()
        event_handler = event_handlers.CheckAppealedEventHandler(check=self)
        event_handler.handle()

    def close(self):
        self.status = CheckStatusesEnum.CLOSED
        self.end_date = datetime.now()
        self.save()
        event_handler = event_handlers.CheckClosedEventHandler(check=self)
        event_handler.handle()


class CheckPerformRequest(models.Model):
    """
    Perform request for check.

    """
    check_obj = models.ForeignKey(Check, on_delete=models.CASCADE, related_name='perform_requests')
    performer = models.ForeignKey('user_profile.User', on_delete=models.CASCADE, related_name='perform_requests')

    class Meta:
        unique_together = ('check_obj', 'performer')

    def approve(self):
        self.check_obj.performer = self.performer
        self.check_obj.status = CheckStatusesEnum.PROCESSING
        self.check_obj.save()
        self.check_obj.perform_requests.all().delete()
        event_handler = event_handlers.CheckProcessingEventHandler(
            check=self.check_obj, performer=self.performer.get_full_name())
        event_handler.handle()
        self._inform_performer()
        self.delete()

    def save(self, *args, **kwargs):
        if not self.performer.is_performer:
            raise ValidationError('Исполнителем должен быть тайный покупатель, сейчас {}'.format(self.performer.status))
        return super().save(*args, **kwargs)

    def _inform_performer(self) -> None:
        """
        Inform performer that his/her perform request was approved.
        """
        site = Site.objects.get_current()
        letter_templates = PerformerLettersTemplates.get()
        subject = letter_templates.apply_subject

        try:
            message = letter_templates.apply_message.format(
                performer=self.performer.get_full_name(),
                check=self.check_obj.title,
                link='https://{}{}'.format(site.domain, self.check_obj.get_absolute_url())
            )
        except Exception:
            message = letter_templates.apply_subject.format(
                performer=self.performer.get_full_name(),
                check=self.check_obj.title,
                link='https://{}{}'.format(site.domain, self.check_obj.get_absolute_url())
            )
        email = EmailMessage(
            subject=subject,
            body=message,
            to=(self.performer.email,)
        )
        email.send()


class CheckPerformInvitation(models.Model):
    """
    Invitation to be performer of this check.
    """
    check_obj = models.ForeignKey(Check, on_delete=models.CASCADE, related_name='perform_invitations')
    performer = models.ForeignKey('user_profile.User', on_delete=models.CASCADE, related_name='perform_invitations')

    class Meta:
        unique_together = ('check_obj', 'performer')

    @classmethod
    def invite(cls, performer, check) -> None:
        """
        Invite performer to given check.

        Creates new invitation class with given parameters and sends an invitation email to performer.
        """
        invitation, created = cls.objects.get_or_create(check_obj=check, performer=performer)
        invitation._send_invitation_letter()

    def accept(self):
        """
        Accept this invitation and become the performer of the check.
        """
        self.check_obj.performer = self.performer
        self.check_obj.make_processing()
        self.delete()

    def _send_invitation_letter(self):
        """
        Send invitation to performer the check to the possible performer.
        """
        site = Site.objects.get_current()

        letter_templates = PerformerLettersTemplates.get()
        subject = letter_templates.invite_subject
        try:
            message = letter_templates.invite_message.format(
                performer=self.performer.get_full_name(),
                check=self.check_obj.title,
                link='https://{}{}'.format(site.domain, self.check_obj.get_absolute_url())
            )
        except Exception:
            message = letter_templates.default_invite.format(
                performer=self.performer.get_full_name(),
                check=self.check_obj.title,
                link='https://{}{}'.format(site.domain, self.check_obj.get_absolute_url())
            )

        email = EmailMessage(
            subject=subject,
            body=message,
            to=(self.performer.email, )
        )
        email.send()

templates/check/available.html
{% extends 'base/base_app.html' %}


{% block meta %}
    <title>{{ page_title }}</title>
{% endblock %}


{% block css %}
    <style>
        .check:hover{
            background-color: #eeeeee !important;
        }
    </style>

{% endblock %}


{% block page-header %}
    {{ page_title }}
{% endblock %}


{% block content %}

    <div class="card">

        <div class="card-body d-flex flex-column justify-content-between p-1">
            <div class="results container-fluid">
                <div class="results-header row bg-grey-300 text-white font-weight-bold m-1 p-2" style="border-radius: 3px">
                    <div class="col-6 col-sm-3 col-lg-1 d-flex">ID</div>
                    <div class="col-6 col-sm-3 col-lg-1 d-flex">Статус</div>
                    <div class="col-6 col-sm-3 col-lg-2 d-flex">Дата начала</div>
                    <div class="col-6 col-sm-3 col-lg-2 d-flex">Дедлайн</div>
                    <div class="col-12 col-sm-9 col-lg-5 d-flex">Цель</div>
                    <div class="col-12 col-sm-3 col-lg-1 d-flex">Награда</div>
                </div>
                {% for check in checks %}
                    <a href="{{ check.get_absolute_url }}" class="d-flex row justify-content-between bg-light m-1 p-2 check" style="border-radius: 3px">
                        <div class="col-6 col-sm-3 col-lg-1 text-black-50">{{ check.id }}</div>
                        <div class="col-6 col-sm-3 col-lg-1"><span class="badge badge-info">{{ check.get_status_display }}</span></div>
                        <div class="col-6 col-sm-3 col-lg-2 text-black-50">{{ check.start_date }}</div>
                        <div class="col-6 col-sm-3 col-lg-2 text-black-50">{{ check.deadline }}</div>
                        <div class="col-12 col-sm-9 col-lg-5 text-black-50">{{ check.target.title }}</div>
                        <div class="col-12 col-sm-3 col-lg-1 text-black-50">{{ check.reward }}руб.</div>
                    </a>
                {% empty %}
                    <div class="m-3">
                        <span class="font-size-lg text-black-50">На данный момент проверок нет</span>
                    </div>
                {% endfor %}

            </div>
        </div>

        {% if is_paginated %}
            <div class="d-flex justify-content-center mt-3 mb-3">

                <ul class="pagination shadow-1">

                    {% if page_obj.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link page-link-white legitRipple"><<</a></li>
                        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link page-link-white legitRipple"><</a></li>
                    {% endif %}
                    <li class="page-item active"><a href="#" class="page-link page-link-white legitRipple">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>

                    {% if page_obj.has_next %}
                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link page-link-white legitRipple">></a></li>
                        <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link page-link-white legitRipple">>></a></li>
                    {% endif %}
                </ul>
            </div>

        {% endif %}


    </div>
{% endblock %}


{% block script %}
    {{ filter.form.media }}
{% endblock %}

templates/check/detail.html
{% extends 'base/base_app.html' %}
{% load staticfiles %}


{% block meta %}
    <title>{{ check.title }}</title>
{% endblock %}

{% block page-header %}
    {% if user.is_staff %}
        <a href="{% url 'check:list' %}">Список проверок</a> /
    {% endif %}
    Проверка
{% endblock %}

{% block header-buttons %}

    {% if user.is_performer %}{# USER IS PERFORMER #}

        {% if check.get_status_display == statuses.AVAILABLE %} {# status avilable #}
            {% if perform_request_exists %} {# check if perform request exist #}
                <button class="btn btn-primary disabled">Заявка создана</button>

            {% else %} {# else show button to create perform request #}
                <form action="{% url 'check:create-perform-request' check.id %}" method="post">
                    {% csrf_token %}
                    {{ perform_request_form }}
                    <input type="submit" value="Заявка на исполнение" class="btn btn-primary">
                </form>
            {% endif %}

        {% elif check.get_status_display == statuses.PROCESSING %}  {# status processing #}
            <form action="{% url 'check:make-filled' check.id %}" method="post">  {# send check to curator form #}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="На проверку">
            </form>
        {% endif %}


    {% elif user.is_customer %} {# USER CUSTOMER #}
        {% if check.get_status_display == statuses.CONFORMATION %}  {# if status is sent for conformation #}

            {# show appeal button #}
            <a href="{% url 'checklist:appeal' check.checklist.id %}" class="btn btn-primary m-1">Аппелировать</a>

            {# show close form #}
            <form action="{% url 'check:make-close' check.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="Закрыть">
            </form>
        {% endif %}

    {% elif user.is_staff %}  {# USER STAFF #}
        <a href="{% url 'check:excel' check.id %}" class="btn btn-primary m-1">Отчет</a>


        {% if check.get_status_display == statuses.CREATED %} {# current status is created #}
            <form action="{% url 'check:make-available' check.id %}" method="post">  {# show make available form #}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="Сделать доступной">
            </form>

        {% elif check.get_status_display == statuses.AVAILABLE %}  {# current status is available #}
            <a href="{% url 'check:appoint-performer' check.id %}" class="btn btn-primary m-1">Назначить исполнителя</a>

        {% elif check.get_status_display == statuses.PROCESSING %} {# current status is processing #}
            <form action="{% url 'check:make-filled' check.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="На проверку">
            </form>

        {% elif check.get_status_display == statuses.FILLED %}  {# current status is filled #}
            <form action="{% url 'check:make-conformation' check.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="На одобрение">
            </form>
            <form action="{% url 'check:make-rework' check.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="На доработку">
            </form>

        {% elif check.get_status_display == statuses.CONFORMATION %}  {# current status is conformation #}
            <form action="{% url 'check:make-close' check.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="Закрыть">
            </form>

        {% elif check.get_status_display == statuses.APPEAL %}  {# current status is appeal #}
            <form action="{% url 'check:make-conformation' check.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="На одобрение">
            </form>
            <form action="{% url 'check:make-close' check.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="Закрыть">
            </form>

        {% elif check.get_status_display == statuses.CLOSED %}  {# current status is closed #}
            <form action="{% url 'check:make-processing' check.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary m-1" value="В работу">
            </form>
        {% endif %}


        <a href="{% url 'check:update' check.id %}" class="btn btn-primary m-1">Редактировать</a>
        <a href="{% url 'check:delete' check.id %}" class="btn btn-danger m-1">Удалить</a>
    {% endif %}

{% endblock %}


{% block content %}
    <div class="card">

        <!-- CHECK NAME -->
        <div class="card-header">
            <h3 class="font-weight-bold text-black-50">{{ check.title }}</h3>
        </div><!-- /CHECK NAME -->


        <!-- CHECK DESCRIPTION -->
        <div class="card-body">

            <div class="row mt-2"> <!-- check id -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Идентификатор: </div>
                <div class="text-black-50 col-6 col-sm-9">{{ check.id }}</div>
            </div>

            <div class="row mt-2">  <!-- check status -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Статус:</div>
                <div class="text-black-50 col-6 col-sm-9"> <span class="badge badge-info">{{ check.get_status_display }}</span></div>
            </div>

            <div class="row mt-2">  <!-- check start date -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Дата начала:</div>
                <div class="text-black-50 col-6 col-sm-9">{{ check.start_date }}</div>
            </div>

            <div class="row mt-2">  <!-- check deadline -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Дедлайн:</div>
                <div class="text-black-50 col-6 col-sm-9">{{ check.deadline }}</div>
            </div>

            <div class="row mt-2">  <!-- check target -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Цель:</div>
                <div class="text-black-50 col-6 col-sm-9">
                    {% if user.is_performer %}
                        {{ check.target.title }}
                    {% else %}
                        <a href="{{ check.target.get_absolute_url }}">{{ check.target.title }}</a>
                    {% endif %}

                </div>
            </div>

            <div class="row mt-2">  <!-- check performer -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Тайный покупатель:</div>

                <div class="text-black-50 col-6 col-sm-9">
                    {% if user.is_customer %}
                        {% if check.performer %}
                            {{ check.performer.get_full_name }}
                        {% elif check.performer_types %}
                            {{ check.performer_typed }}
                        {% else %}
                            Не указан
                        {% endif %}

                    {% else %}
                        {% if check.performer %}
                            <a href="{{ check.performer.get_absolute_url }}">{{ check.performer.get_full_name }}</a>
                        {% elif check.performer_types %}
                            {{ check.performer_typed }}
                        {% else %}
                            Не указан
                        {% endif %}
                    {% endif %}
                </div>
            </div>

            <div class="row mt-2">  <!-- check checklist -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Чек-лист:</div>
                <div class="text-black-50 col-6 col-sm-9">
                    {% if user.is_staff %}
                        <a href="{% url 'checklist:constructor:constructor' check.checklist.id %}">Конструктор</a> |
                        <a href="{% url 'checklist:detail' check.checklist.id %}">Просмотр</a> |
                        <a href="{% url 'checklist:update' check.checklist.id %}">Редактировать</a> |

                    {% elif user.is_customer %}
                        <a href="{% url 'checklist:detail' check.checklist.id %}">Просмотр</a>
                        {% if user.customer_profile.is_boss %}
                           | <a href="{% url 'checklist:update' check.checklist.id %}">Редактировать</a>
                        {% endif %}

                    {% elif user.is_performer %}
                        {% if user == check.performer %}
                            {% if check.get_status_display == statuses.PROCESSING %}
                                <a href="{% url 'checklist:update' check.checklist.id %}">Редактировать</a>
                            {% else %}
                                <a href="{% url 'checklist:detail' check.checklist.id %}">Просмотр</a>
                            {% endif %}
                        {% else %}
                            Чек-лист будет доступен после одобрения
                        {% endif %}

                    {% endif %}

                </div>
            </div>

            <div class="row mt-2">  <!-- check instruction -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Инструкция:</div>
                <div class="text-black-50 col-6 col-sm-9">
                    {% if check.instruction %}
                        <a href="{{ check.instruction.get_absolute_url }}">Просмотр</a>

                    {% else %}
                        <span class="text-black-50">Не указана</span>
                    {% endif %}
                </div>
            </div>

            <div class="row mt-2">  <!-- check curator -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Куратор:</div>
                <div class="text-black-50 col-6 col-sm-9">
                    {% if user.is_staff %}
                        <a href="{{ check.curator.get_absolute_url }}">{{ check.curator.get_full_name }}</a>
                    {% else %}
                        {{ check.curator.get_full_name }}
                    {% endif %}
                </div>
            </div>

            <div class="row mt-2"> <!-- check comment -->
                <div class="text-black-50 col-6 col-sm-3 font-weight-bold">Комментарий:</div>
                <div class="text-black-50 col-6 col-sm-9">{{ check.comment }}</div>
            </div>

        </div>
    </div>

{% endblock %}