ghost_shopper/check/urls.py
from django.urls import path

from . import views

app_name = 'check'


urlpatterns = [

    # different check list urls
    path('', views.ChecksListView.as_view(), name='list'),
    path('available', views.AvailableChecksListView.as_view(), name='available'),
    path('performer/<int:pk>/closed', views.PerformerClosedChecksListView.as_view(), name='performer-closed'),
    path('performer/<int:pk>/current', views.PerformerCurrentChecksListView.as_view(), name='performer-current'),

    path('create', views.CheckCreateView.as_view(), name='create'),
    path('<int:pk>', views.CheckDetailView.as_view(), name='detail'),
    path('<int:pk>/update', views.CheckUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.CheckDeleteView.as_view(), name='delete'),
    path('<int:pk>/excel', views.CheckFileGenerateView.as_view(), name='excel'),

    # check performer requests urls
    path('<int:pk>/appoint-performer', views.CheckAppointPerformerView.as_view(), name='appoint-performer'),
    path('<int:pk>/perform-request/create',
         views.CheckPerformRequestCreateView.as_view(),
         name='create-perform-request'),
    path('perform-request/<int:pk>/approve',
         views.CheckPerformRequestApproveView.as_view(),
         name='approve-perform-request'),

    # check change statuses urls
    path('<int:pk>/change-status/available', views.CheckMakeAvailableView.as_view(), name='make-available'),
    path('<int:pk>/make-processing', views.CheckMakeProcessingView.as_view(), name='make-processing'),
    path('<int:pk>/change-status/filled', views.CheckMakeFilledView.as_view(), name='make-filled'),
    path('<int:pk>/change-status/rework', views.CheckSendForReworkView.as_view(), name='make-rework'),
    path('<int:pk>/change-status/conformation',
        views.CheckSendForCustomerConformationView.as_view(),
        name='make-conformation'),
    path('<int:pk>/change-status/close', views.CheckCloseView.as_view(), name='make-close'),
]

ghost_shopper/organisation_tree/urls.py
from django.urls import path
from . import views


app_name = 'organisation'


urlpatterns = [
    path('', views.OrganisationListView.as_view(), name='list'),
    path('create', views.OrganisationCreateView.as_view(), name='create'),
    path('<int:pk>', views.OrganisationDetailView.as_view(), name='detail'),
    path('<int:pk>/update', views.OrganisationUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.OrganisationDeleteView.as_view(), name='delete'),
    path('<int:pk>/statistics', views.OrganisationStatisticsView.as_view(), name='statistics'),

    path('<int:pk>/create/employee', views.CreateEmployeeView.as_view(), name='create-employee'),

    path('<int:pk>/docs', views.OrganisationDocsListView.as_view(), name='docs'),
    path('docs/<int:pk>', views.OrganisationDocsStorageDetailView.as_view(), name='docs-detail'),
    path('docs/<int:pk>/generate-current', views.OrganisationDocsGenerateCurrentView.as_view(), name='generate'),
    path('docs/<int:pk>/download/<slug:type>', views.send_document, name='docs-download'),

    path('<int:pk>/checks', views.OrganisationChecksListView.as_view(), name='checks'),
    path('<int:pk>/current-checks', views.OrganisationCurrentChecksListView.as_view(), name='current-checks'),

    path('autocomplete', views.OrganisationAutocompleteView.as_view(), name='autocomplete'),
    path('autocomplete/node', views.OrganisationNodeAutocompleteView.as_view(), name='autocomplete-node'),
]

ghost_shopper/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('ghost_shopper.index_page.urls', namespace='index_page')),

    path('summernote/', include('django_summernote.urls')),

    path('core/', include('ghost_shopper.core.urls', namespace='core')),
    path('admin/', include('ghost_shopper.admin.urls', namespace='admin')),
    path('project/', include('ghost_shopper.project.urls', namespace='project')),
    path('profile/', include('ghost_shopper.auth.urls', namespace='auth')),
    path('profile/', include('ghost_shopper.user_profile.urls', namespace='profile')),
    path('check/', include('ghost_shopper.check.urls', namespace='check')),
    path('chat/', include('ghost_shopper.organisation_chat.urls', namespace='chat')),
    path('checklist/', include('ghost_shopper.checklist.urls', namespace='checklist')),
    path('organisation/', include('ghost_shopper.organisation_tree.urls', namespace='organisation')),
    path('instruction/', include('ghost_shopper.instruction.urls', namespace='instruction')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ghost_shopper/check/models.py
from datetime import date, datetime

from django.conf import settings
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.db import models
from django.urls import reverse

from ghost_shopper.core.models import PerformerLettersTemplates
from ghost_shopper.news import event_handlers

from .enums import CHECK_TYPES, CheckStatusesEnum


class UsualChecksManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=CHECK_TYPES['USUAL'])


class Check(models.Model):
    """
    Check object.
    """
    project = models.OneToOneField('project.Project', on_delete=models.SET_NULL, null=True, blank=True,
                                related_name='check_obj', verbose_name='Проект')
    status = models.CharField(max_length=30, choices=tuple(CheckStatusesEnum.values.items()),
                              default=CheckStatusesEnum.CREATED, verbose_name='Статус')
    type = models.CharField(max_length=20, choices=tuple(CHECK_TYPES.items()), default=CHECK_TYPES['USUAL'],
                            verbose_name='Тип')
    kind = models.ForeignKey('core.CheckKind', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Тип')
    start_date = models.DateField(null=True, blank=True, verbose_name='Дата начала')
    deadline = models.DateField(null=True, blank=True, verbose_name='Дедлайн')
    end_date = models.DateField(null=True, blank=True, verbose_name='Окончание')
    target = models.ForeignKey(
        'organisation_tree.OrganisationTreeNode',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name='Цель'
    )
    instruction = models.ForeignKey(
        'instruction.Instruction', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Инструкция')
    performer = models.ForeignKey(
        'user_profile.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='performer',
        verbose_name='Исполнитель')
    curator = models.ForeignKey(
        'user_profile.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='checks',
        verbose_name='Куратор')
    reward = models.PositiveSmallIntegerField(default=0, verbose_name='Награда(руб.)')
    was_sent_to_rework = models.BooleanField(default=False, verbose_name='Была отправлена на доработку')
    was_appealed = models.BooleanField(default=False, verbose_name='Была аппеляция')
    conformation_period = models.PositiveSmallIntegerField('Дней на аппеляцию', default=1)
    comment = models.TextField(blank=True, null=True, verbose_name='Комментарий')

    sent_for_conformation_date = models.DateField(null=True, blank=True)

    objects = models.Manager()
    usual = UsualChecksManager()

    class Meta:
        ordering = ('start_date', )
        verbose_name = 'Проверка'
        verbose_name_plural = 'Проверки'

    @property
    def title(self):
        return self.__str__()

    def __str__(self):
        name = self.target.title if self.target else self.id
        return 'Проверка {}'.format(name)

    def get_absolute_url(self):
        return reverse('check:detail', args=(self.id,))

    def clone(self, new_target=None) -> None:
        """
        Clone this check.
        Returns:
            new_check (Check): new cloned check object.
        """
        instruction = self.instruction
        checklist = self.checklist

        new_check = self
        new_check.id = None
        new_check.project = None
        new_check.target = new_target
        new_check.status = CheckStatusesEnum.AVAILABLE
        new_check.type = CHECK_TYPES['USUAL']
        new_check.instruction = instruction
        new_check.save()
        new_check.checklist.delete()

        checklist.clone(new_check)
        return new_check

    def make_available(self):
        self.status = CheckStatusesEnum.AVAILABLE
        self.save()
        event_handler = event_handlers.CheckAvailableEventHandler(check=self)
        event_handler.handle()

    def make_processing(self):
        self.status = CheckStatusesEnum.PROCESSING
        self.save()
        self.perform_requests.all().delete()
        performer_name = self.performer.get_full_name() if self.performer else self.performer_typed
        event_handler = event_handlers.CheckProcessingEventHandler(self, performer_name)
        event_handler.handle()

    def make_filled(self):
        self.status = CheckStatusesEnum.FILLED
        self.save()
        event_handler = event_handlers.CheckFilledEventHandler(check=self)
        event_handler.handle()

    def send_for_rework(self):
        self.status = CheckStatusesEnum.PROCESSING
        self.was_sent_to_rework = True
        self.save()
        event_handler = event_handlers.CheckSentToReworkEventHandler(check=self)
        event_handler.handle()

    def send_for_conformation(self):
        self.status = CheckStatusesEnum.CONFORMATION
        self.sent_for_conformation_date = date.today()
        self.save()
        event_handler = event_handlers.CheckSentForConformation(check=self)
        event_handler.handle()

    def appeal(self):
        self.status = CheckStatusesEnum.APPEAL
        self.was_appealed = True
        self.save()
        event_handler = event_handlers.CheckAppealedEventHandler(check=self)
        event_handler.handle()

    def close(self):
        self.status = CheckStatusesEnum.CLOSED
        self.end_date = datetime.now()
        self.save()
        event_handler = event_handlers.CheckClosedEventHandler(check=self)
        event_handler.handle()


class CheckPerformRequest(models.Model):
    """
    Perform request for check.

    """
    check_obj = models.ForeignKey(Check, on_delete=models.CASCADE, related_name='perform_requests')
    performer = models.ForeignKey('user_profile.User', on_delete=models.CASCADE, related_name='perform_requests')

    class Meta:
        unique_together = ('check_obj', 'performer')

    def approve(self):
        self.check_obj.performer = self.performer
        self.check_obj.status = CheckStatusesEnum.PROCESSING
        self.check_obj.save()
        self.check_obj.perform_requests.all().delete()
        event_handler = event_handlers.CheckProcessingEventHandler(
            check=self.check_obj, performer=self.performer.get_full_name())
        event_handler.handle()
        self._inform_performer()
        self.delete()

    def save(self, *args, **kwargs):
        if not self.performer.is_performer:
            raise ValidationError('Исполнителем должен быть тайный покупатель, сейчас {}'.format(self.performer.status))
        return super().save(*args, **kwargs)

    def _inform_performer(self) -> None:
        """
        Inform performer that his/her perform request was approved.
        """
        site = Site.objects.get_current()
        letter_templates = PerformerLettersTemplates.get()
        subject = letter_templates.apply_subject

        try:
            message = letter_templates.apply_message.format(
                performer=self.performer.get_full_name(),
                check=self.check_obj.title,
                link='https://{}{}'.format(site.domain, self.check_obj.get_absolute_url())
            )
        except Exception:
            message = letter_templates.apply_subject.format(
                performer=self.performer.get_full_name(),
                check=self.check_obj.title,
                link='https://{}{}'.format(site.domain, self.check_obj.get_absolute_url())
            )
        email = EmailMessage(
            subject=subject,
            body=message,
            to=(self.performer.email,)
        )
        email.send()


class CheckPerformInvitation(models.Model):
    """
    Invitation to be performer of this check.
    """
    check_obj = models.ForeignKey(Check, on_delete=models.CASCADE, related_name='perform_invitations')
    performer = models.ForeignKey('user_profile.User', on_delete=models.CASCADE, related_name='perform_invitations')

    class Meta:
        unique_together = ('check_obj', 'performer')

    @classmethod
    def invite(cls, performer, check) -> None:
        """
        Invite performer to given check.

        Creates new invitation class with given parameters and sends an invitation email to performer.
        """
        invitation, created = cls.objects.get_or_create(check_obj=check, performer=performer)
        invitation._send_invitation_letter()

    def accept(self):
        """
        Accept this invitation and become the performer of the check.
        """
        self.check_obj.performer = self.performer
        self.check_obj.make_processing()
        self.delete()

    def _send_invitation_letter(self):
        """
        Send invitation to performer the check to the possible performer.
        """
        site = Site.objects.get_current()

        letter_templates = PerformerLettersTemplates.get()
        subject = letter_templates.invite_subject
        try:
            message = letter_templates.invite_message.format(
                performer=self.performer.get_full_name(),
                check=self.check_obj.title,
                link='https://{}{}'.format(site.domain, self.check_obj.get_absolute_url())
            )
        except Exception:
            message = letter_templates.default_invite.format(
                performer=self.performer.get_full_name(),
                check=self.check_obj.title,
                link='https://{}{}'.format(site.domain, self.check_obj.get_absolute_url())
            )

        email = EmailMessage(
            subject=subject,
            body=message,
            to=(self.performer.email, )
        )
        email.send()

templates/organisation/checks.html
{% extends 'base/base_app.html' %}
{% load staticfiles %}


{% block meta %}
    <title>Завершенные проверки</title>
{% endblock %}


{% block css %}
    <style>
        .check:hover{
            background-color: #eeeeee !important;
        }
        .select2-container{
            width: 100%;
            min-width: 100% !important;
        }

        .select2-selection--single{
            border: none !important;
            border-bottom: 1px solid #ddd!important;
            border-radius: 0!important;
            display: flex;
            align-items: center;

            height: auto!important;
        }

        .select2-search--dropdown:after{
            display: none;
        }
    </style>

{% endblock %}


{% block page-header %}
    Проверки
{% endblock %}


{% block content %}

    <form action="" method="get">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="mb-2 mt-2">
                            <label class="text-black-50 font-weight-bold" for="{{ filter.form.start_date.id_for_label }}">Дата начала</label>
                            <div class="d-flex align-items-center">{{ filter.form.start_date }}</div>
                        </div>
                        <div class="mb-2 mt-2">
                            <label class="text-black-50 font-weight-bold" for="{{ filter.form.end_date.id_for_label }}">Дата окончания</label>
                            <div class="d-flex align-items-center">{{ filter.form.end_date }}</div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="mt-2 mb-2">
                            <label class="text-black-50 font-weight-bold" for="{{ filter.form.target.id_for_label }}">Цель</label>
                            {{ filter.form.target }}
                        </div>
                        <div class="mt-2 mb-2">
                            <label class="text-black-50 font-weight-bold" for="{{ filter.form.curator.id_for_label }}">Куратор</label>
                            {{ filter.form.curator }}
                        </div>
                    </div>
                </div>
            </div>


        </div>
        <div class="row d-flex justify-content-center mb-2">
            <input type="submit" value="Показать" class="btn btn-dark m-1">
            <a href="{% url 'organisation:checks' organisation_id %}" class="btn btn-light m-1">Очистить</a>
        </div>


    </form>


    <div class="card">

        <div class="card-body d-flex flex-column justify-content-between">
            <div class="results">
                <div class="results-header row bg-light m-1 p-2" style="border-radius: 3px">
                    <div class="col-1 d-flex font-weight-bold text-black-50">ID</div>
                    <div class="col-1 d-flex font-weight-bold text-black-50">Статус</div>
                    <div class="col-1 d-flex font-weight-bold text-black-50">Дата начала</div>
                    <div class="col-1 d-flex font-weight-bold text-black-50">Дедлайн</div>
                    <div class="col-3 d-flex font-weight-bold text-black-50">Цель</div>
                    <div class="col-2 d-flex font-weight-bold text-black-50">Тайный покупатель</div>
                    <div class="col-2 d-flex font-weight-bold text-black-50">Куратор</div>
                    <div class="col-1 d-flex font-weight-bold text-black-50">Награда</div>
                </div>
                {% for check in checks %}
                    <a href="{{ check.get_absolute_url }}" class="d-flex row justify-content-between bg-light m-1 p-2 check" style="border-radius: 3px">
                        <div class="col-1  text-black-50">{{ check.id }}</div>
                        <div class="col-1"><span class="badge badge-info">{{ check.get_status_display }}</span></div>
                        <div class="col-1 text-black-50">{{ check.start_date }}</div>
                        <div class="col-1 text-black-50">{{ check.deadline }}</div>
                        <div class="col-3 text-black-50">{{ check.target.title }}</div>
                        <div class="col-2 text-black-50">{{ check.performer }}</div>
                        <div class="col-2 text-black-50">{{ check.curator }}</div>
                        <div class="col-1 text-black-50">{{ check.reward }}руб.</div>
                    </a>

                {% endfor %}

            </div>
        </div>

        {% if is_paginated %}
            <div class="d-flex justify-content-center mt-3 mb-3">

                <ul class="pagination shadow-1">

                    {% if page_obj.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link page-link-white legitRipple"><<</a></li>
                        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link page-link-white legitRipple"><</a></li>
                    {% endif %}
                    <li class="page-item active"><a href="#" class="page-link page-link-white legitRipple">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>

                    {% if page_obj.has_next %}
                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link page-link-white legitRipple">></a></li>
                        <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link page-link-white legitRipple">>></a></li>
                    {% endif %}
                </ul>
            </div>

        {% endif %}


    </div>


{% endblock %}


{% block script %}
    {{ filter.form.media }}
    <script type="text/javascript" src="{% static 'assets/js/plugins/pickers/pickadate/picker.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/plugins/pickers/pickadate/picker.date.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/plugins/pickers/pickadate/picker.time.js' %}"></script>
    <script>
        let options = {
            monthsFull: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
            monthsShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
            weekdaysFull: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
            weekdaysShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            format: 'yyyy-mm-dd'
        };
        $('.pickadate').pickadate(options);
    </script>
{% endblock %}

templates/organisation/current_checks.html
{% extends 'base/base_app.html' %}
{% load staticfiles %}


{% block meta %}
    <title>Проверки</title>
{% endblock %}


{% block css %}
    <style>
        .check:hover{
            background-color: #eeeeee !important;
        }
    </style>

{% endblock %}


{% block page-header %}
    Проверки
{% endblock %}

{% block content %}

    <div class="card">

        <div class="card-body d-flex flex-column justify-content-between">
            <div class="results">
                <div class="results-header row bg-light m-1 p-2" style="border-radius: 3px">
                    <div class="col-1 d-flex font-weight-bold text-black-50">ID</div>
                    <div class="col-1 d-flex font-weight-bold text-black-50">Статус</div>
                    <div class="col-1 d-flex font-weight-bold text-black-50">Дата начала</div>
                    <div class="col-1 d-flex font-weight-bold text-black-50">Дедлайн</div>
                    <div class="col-3 d-flex font-weight-bold text-black-50">Цель</div>
                    <div class="col-2 d-flex font-weight-bold text-black-50">Тайный покупатель</div>
                    <div class="col-2 d-flex font-weight-bold text-black-50">Куратор</div>
                    <div class="col-1 d-flex font-weight-bold text-black-50">Награда</div>
                </div>
                {% for check in checks %}
                    <a href="{{ check.get_absolute_url }}" class="d-flex row justify-content-between bg-light m-1 p-2 check" style="border-radius: 3px">
                        <div class="col-1  text-black-50">{{ check.id }}</div>
                        <div class="col-1"><span class="badge badge-info">{{ check.get_status_display }}</span></div>
                        <div class="col-1 text-black-50">{{ check.start_date|date:'d.m.Y' }}</div>
                        <div class="col-1 text-black-50">{{ check.deadline|date:'d.m.Y' }}</div>
                        <div class="col-3 text-black-50">{{ check.target.title }}</div>
                        <div class="col-2 text-black-50">{{ check.performer }}</div>
                        <div class="col-2 text-black-50">{{ check.curator }}</div>
                        <div class="col-1 text-black-50">{{ check.reward }}руб.</div>
                    </a>

                {% endfor %}

            </div>
        </div>

        <div class="d-flex justify-content-center mt-3 mb-3">

            <ul class="pagination shadow-1">

                {% if page_obj.has_previous %}
                    <li class="page-item"><a href="?page=1" class="page-link page-link-white legitRipple"><<</a></li>
                    <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link page-link-white legitRipple"><</a></li>
                {% endif %}
                <li class="page-item active"><a href="#" class="page-link page-link-white legitRipple">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link page-link-white legitRipple">></a></li>
                    <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link page-link-white legitRipple">>></a></li>
                {% endif %}
            </ul>
        </div>

    </div>


{% endblock %}


{% block script %}
    {{ filter.form.media }}
    <script type="text/javascript" src="{% static 'assets/js/plugins/pickers/pickadate/picker.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/plugins/pickers/pickadate/picker.date.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/plugins/pickers/pickadate/picker.time.js' %}"></script>
    <script>
        let options = {
            monthsFull: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
            monthsShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
            weekdaysFull: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
            weekdaysShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            format: 'yyyy-mm-dd'
        };
        $('.pickadate').pickadate(options);
    </script>
{% endblock %}

templates/organisation/docs-detail.html
{% extends 'base/base_app.html' %}
{% load staticfiles %}


{% block content %}
    <div class="card">
        <div class="card-header">
            <h3 class="text-black-50 font-weight-bold">{{ storage }}</h3>
        </div>

        <div class="card-body">
            {% for doc_container in storage.documents.all %}
                <div class="p-2 bg-light m-1">
                    <h6>{{ doc_container.organisation_node.full_title }}</h6>
                    <a  href="{% url 'organisation:docs-download' doc_container.id "payment" %}">Cчет на оплату</a>
                    <a  href="{% url 'organisation:docs-download' doc_container.id "agreement" %}" download>Соглашение</a>
                </div>

            {% endfor %}

        </div>
    </div>
{% endblock %}

templates/organisation/docs-list.html
{% extends 'base/base_app.html' %}

{% block header-buttons %}
    <a class="btn btn-primary" href="{% url 'organisation:generate' organisation.id %}">Создать текущие</a>
{% endblock %}


{% block content %}

    <!-- PAGE HEADER -->
    <div class="card">
        <div class="card-header">
            <h4 class="text-black-50 font-weight-bold">Документы организации</h4>
        </div>
    </div><!-- /PAGE HEADER -->


    <!-- DOCS LIST -->
    <div class="card">

        <div class="card-body d-flex flex-column justify-content-between">
            <div class="results">
                {% for document in docs %}
                    <a href="{{ document.get_absolute_url }}" class="d-flex row bg-light m-1 p-2 check" style="border-radius: 3px">
                        <div class="text-black-50">{{ document.id }}</div>
                        <div class="text-black-50 font-weight-bold pl-2">{{ document }}</div>
                    </a>

                {% empty %}
                    <h5 class="text-black-50 font-weight-bold">У данной организации пока нет отчетных документов</h5>

                {% endfor %}

            </div>
        </div>

        {% if is_paginated %}
            <div class="d-flex justify-content-center mt-3 mb-3">

                <ul class="pagination shadow-1">

                    {% if page_obj.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link page-link-white legitRipple"><<</a></li>
                        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link page-link-white legitRipple"><</a></li>
                    {% endif %}
                    <li class="page-item active"><a href="#" class="page-link page-link-white legitRipple">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>

                    {% if page_obj.has_next %}
                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link page-link-white legitRipple">></a></li>
                        <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link page-link-white legitRipple">>></a></li>
                    {% endif %}
                </ul>
            </div>

        {% endif %}


    </div><!-- /DOCS LIST -->

{% endblock %}

templates/organisation/update.html
{% extends 'base/base_app.html' %}

{% block meta %}
    <title>Редактировать узелл организации</title>
{% endblock %}

{% block page-header %}
    Редактировать узел организации
{% endblock %}


{% block header-buttons %}
    <input type="submit" form="organisation-name" class="btn btn-primary m-2" value="Сохранить">
{% endblock %}

{% block content %}

    <!-- PAGE HEADER -->
    <div class="card">
        <div class="card-header">
            <h3 class="text-black-50 font-weight-bold">Редактировать узел организации</h3>
        </div>
    </div><!-- /PAGE HEADER -->


    <!-- FORM -->
    <div class="card">
        <div class="card-body">
            <form method="post" id="organisation-name">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <span class="danger">{{ form.non_field_errors.as_text }}</span>
                {% endif %}

                {% for field in form.visible_fields %}
                    <div class="form-group row">
                        <label class="col-12 col-lg-3 text-black-50 font-weight-bold" for="{{ form.status.id_for_label }}">
                            {{ field.label }} :
                        </label>
                        <div class="col-12 col-lg-9 d-flex row">
                            {{ field }}
                        </div>
                        {% if field.errors %}
                            <span class="text-danger-400">{{ field.errors.as_text }}</span>
                        {% endif %}
                    </div>
                {% endfor %}

                {% for field in form.hidden_fields %}
                    {{ field }}
                {% endfor %}

            </form>
        </div>
    </div><!-- /FORM -->

{% endblock %}